/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TraceListenerImpl */

#ifndef _Included_TraceListenerImpl
#define _Included_TraceListenerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TraceListenerImpl
 * Method:    doSendMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TraceListenerImpl_doSendMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TraceListenerImpl
 * Method:    soSendError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_TraceListenerImpl_soSendError
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
